# https://www.home-assistant.io/integrations/default_config/
default_config:

import_statistics:

http:
api:
# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.import_statistics: debug

template:
  - sensor:
      - name: esp32_bathroom_bathroomtempsensor
        state_class: measurement
        unit_of_measurement: "°C"
        state: "{{ 1 }}"
      - name: esp32_soundroom_soundroomtempsensor
        state_class: measurement
        unit_of_measurement: "°C"
        state: "{{ 2 }}"
      - name: solaredge_i2_ac_energy_kwh
        state_class: total_increasing
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ 43081 }}"
      - name: go_echarger_238557_wh
        state_class: total_increasing
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ 8832 }}"
      - name: test_case_1
        state_class: total_increasing
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ 100 }}"
      - name: test_case_2
        state_class: total_increasing
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ 200 }}"
      - name: test_case_3
        state_class: total_increasing
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ 300 }}"
      - name: imp_before
        state_class: total_increasing
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ 3 }}"
      - name: imp_after
        state_class: total_increasing
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{ 3 }}"
